import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Image from "next/image";

import ClientTourProvider from "./ClientTourProvider";
// ⭐ 新增：引入 ThemeProvider 与切换按钮
import { ThemeProvider } from "./_lib/theme-context";
import ThemeToggle from "@/components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background text-foreground transition-colors`}
      >
        {}
        <ThemeProvider>
          <ClientTourProvider>
            <div className="flex flex-col h-screen">
              {/* === Header === */}
              <header
                className="flex items-center justify-between
                           py-2 px-4 border-b border-border dark:border-border/60"
              >
                <div className="flex items-center">
                  <Image src="/Logo.png" alt="Logo" width={80} height={80} />
                  <h1 className="text-3xl font-bold ml-4">AuditVisualizer</h1>
                </div>
                {}
                <ThemeToggle />
              </header>

              {/* === Main content === */}
              <main className="flex flex-col flex-grow bg-background">
                {children}
              </main>
            </div>
          </ClientTourProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
